apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: skander:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: "jdbc:mysql://192.168.50.147:3306/quiz_db" 
            - name: KUBERNETES_ENV
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      #nodePort: 31000
