apiVersion: apps/v1
kind: Deployment
metadata:
  name: depapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: skander2/skander:latest
          ports:
            - containerPort: 8080
          env:
          - name: USER
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: user
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: password

          - name: URL
            valueFrom:
              configMapKeyRef:
                name: mysqlconfig
                key: url
  

---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31500
---
apiVersion: v1
kind: Service
metadata:
  name: appclusterip
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
